-- ============================================================
-- 003_bootstrap_admin.sql
-- SUPERSEDED by 004_first_admin_bootstrap.sql
--
-- This migration was written before the email-matching approach
-- was identified as incorrect.  It is kept as a no-op so that
-- environments that already applied it do not break.
-- All bootstrap logic is in 004_first_admin_bootstrap.sql.
-- ============================================================
